name: Deploy to ECR

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Push to ECR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t public.ecr.aws/i0c1z9z6/photolab:latest .
        docker push public.ecr.aws/i0c1z9z6/photolab
